motor:
  type: solid
  thrust_source: motors/Yaripo.eng
  burn_time: 3.0
  dry_mass: 8.416
  dry_inertia:
  - 0.54060753
  - 0.54060196
  - 0.025867792
  center_of_dry_mass_position: 0.358
  grains_center_of_mass_position: 0.261
  grain_number: 4
  grain_separation: 0.002
  grain_density: 1815.0
  grain_outer_radius: 0.058
  grain_initial_inner_radius: 0.02
  grain_initial_height: 0.129
  nozzle_radius: 0.03
  throat_radius: 0.0103
  interpolation_method: linear
  coordinate_system_orientation: combustion_chamber_to_nozzle
  nozzle_position: 0.7233
